// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef _MARKET_VIEWER_UI_H
#define _MARKET_VIEWER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_homeScreen.h"
#include "ui_brightnessScreen.h"
#include "ui_volumeScreen.h"
#include "ui_wifiScreen.h"
#include "ui_screensScreen.h"
#include "ui_cryptoScreen.h"
#include "ui_marketDataSettingScreen.h"
#include "ui_stockScreen.h"
#include "ui_clockScreen.h"
#include "ui_timerScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * elementBlink_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1314322640);    // assets/power-icon.png
LV_IMG_DECLARE(ui_img_650757212);    // assets/reboot-icon.png
LV_IMG_DECLARE(ui_img_1826884842);    // assets/brightness-icon.png
LV_IMG_DECLARE(ui_img_367695115);    // assets/volume-icon.png
LV_IMG_DECLARE(ui_img_871200326);    // assets/rotate-icon.png
LV_IMG_DECLARE(ui_img_555948897);    // assets/monitor-icon.png
LV_IMG_DECLARE(ui_img_301975032);    // assets/battery-empty-icon.png
LV_IMG_DECLARE(ui_img_1272477160);    // assets/wifi-icon.png
LV_IMG_DECLARE(ui_img_1702299517);    // assets/return-icon.png
LV_IMG_DECLARE(ui_img_536642073);    // assets/check-icon.png
LV_IMG_DECLARE(ui_img_9953116);    // assets/wrench-icon.png
LV_IMG_DECLARE(ui_img_788343386);    // assets/reset-icon.png
LV_IMG_DECLARE(ui_img_936315526);    // assets/refresh-icon.png
LV_IMG_DECLARE(ui_img_red_background_png);    // assets/red_background.png
LV_IMG_DECLARE(ui_img_121694436);    // assets/crypto-icon.png
LV_IMG_DECLARE(ui_img_green_background_png);    // assets/green_background.png
LV_IMG_DECLARE(ui_img_1458903039);    // assets/stock-icon.png
LV_IMG_DECLARE(ui_img_gauge_background_png);    // assets/gauge_background.png
LV_IMG_DECLARE(ui_img_needle_small_png);    // assets/needle_small.png
LV_IMG_DECLARE(ui_img_needle_big_png);    // assets/needle_big.png
LV_IMG_DECLARE(ui_img_purple_background_png);    // assets/purple_background.png
LV_IMG_DECLARE(ui_img_1970864515);    // assets/play-icon.png
LV_IMG_DECLARE(ui_img_461506120);    // assets/timer-icon.png
LV_IMG_DECLARE(ui_img_81954201);    // assets/pause-icon.png

// FONTS
LV_FONT_DECLARE(ui_font_digitsFont100);
LV_FONT_DECLARE(ui_font_digitsFontSmall);
LV_FONT_DECLARE(ui_font_Mono20);
LV_FONT_DECLARE(ui_font_mono30);
LV_FONT_DECLARE(ui_font_mono40);
LV_FONT_DECLARE(ui_font_mono50);
LV_FONT_DECLARE(ui_font_monoBold100);
LV_FONT_DECLARE(ui_font_monoBold20);
LV_FONT_DECLARE(ui_font_monoBold50);
LV_FONT_DECLARE(ui_font_monoBold60);
LV_FONT_DECLARE(ui_font_monoBold80);
LV_FONT_DECLARE(ui_font_monoLight30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
