// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_CRYPTOSCREEN_H
#define UI_CRYPTOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_cryptoScreen
extern void ui_cryptoScreen_screen_init(void);
extern void ui_cryptoScreen_screen_destroy(void);
extern void ui_event_cryptoScreen(lv_event_t * e);
extern lv_obj_t * ui_cryptoScreen;
extern lv_obj_t * ui_cryptoGraphPanel;
extern lv_obj_t * ui_cryptoAthArc;
extern lv_obj_t * ui_cryptoPriceLabel;
extern lv_obj_t * ui_cryptoPriceChangeLabel;
extern lv_obj_t * ui_cryptoTimeFrameLabel;
extern lv_obj_t * ui_cryptoAssetCurrencyLabel;
extern lv_obj_t * ui_cryptoAssetCurrencyCont;
extern lv_obj_t * ui_cryptoAssetNameLabel;
extern lv_obj_t * ui_cryptoCurrencyLabel;
extern lv_obj_t * ui_cryptoIcon;
extern lv_obj_t * ui_cryptoAthLabel;
extern lv_obj_t * ui_cryptoZeroLabel1;
extern lv_obj_t * ui_cryptoAthChangeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

