// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setButtonsStatusHomeScreen(lv_event_t * e);
void swipeNextScreen(lv_event_t * e);
void toggleTurnOff(lv_event_t * e);
void restartDevice(lv_event_t * e);
void toggleRotationSettings(lv_event_t * e);
void saveBrightness(lv_event_t * e);
void setBrightnessFromArc(lv_event_t * e);
void saveVolume(lv_event_t * e);
void setVolumeFromArc(lv_event_t * e);
void updateWifiScreenStatusOnLoad(lv_event_t * e);
void openWifiPortal(lv_event_t * e);
void resetWifiConfig(lv_event_t * e);
void handleScreensScreenLoad(lv_event_t * e);
void refetchScreens(lv_event_t * e);
void swipePrevScreen(lv_event_t * e);
void requestScreenDataRefresh(lv_event_t * e);
void switchToHomeScreen(lv_event_t * e);
void exitMarketDataSetting(lv_event_t * e);
void marketDataSettingScreenLoad(lv_event_t * e);
void simpleDisplaySwitchToggle(lv_event_t * e);
void displayGraphSwitchToggle(lv_event_t * e);
void candleChartSwitchToggle(lv_event_t * e);
void timerResetPressed(lv_event_t * e);
void timerStartPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
