// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: first_test

#include "ui.h"
#include <Arduino.h>
#include "HardwareDriver.h"
#include "esp32-hal-cpu.h"
#include "AudioManager.h"
#include "WifiConfig.h"
#include "ui_events_helper.h"
#include "ScreensManager.h"
#include "messageDisplay.h"
#include "GuiManager.h"

#include "AudioManager.h"

//global shield to not control screen when it is off
lv_obj_t * blackout_shield = NULL;

void toggleTurnOff(lv_event_t * e)
{        
       
    if (isScreenOff) {
        Serial.println("Screen waking up!");
        
        setCpuFrequencyMhz(240); // drop speed when device is 'turned on'
        set_brightness_percentage(currentBrightness);
        isScreenOff = false;

        if (blackout_shield != NULL) {
            lv_obj_del(blackout_shield);
            blackout_shield = NULL; 
        }
    } else {
        Serial.println("Screen going to sleep");

        set_brightness(0);
        isScreenOff = true;

        //CREATE THE SHIELD
        blackout_shield = lv_obj_create(lv_layer_top());        
        lv_obj_set_size(blackout_shield, LV_PCT(100), LV_PCT(100));        
        lv_obj_set_style_bg_opa(blackout_shield, 0, 0);
        lv_obj_set_style_border_width(blackout_shield, 0, 0);        
        lv_obj_add_flag(blackout_shield, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_clear_flag(blackout_shield, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_add_event_cb(blackout_shield, toggleTurnOff, LV_EVENT_CLICKED, NULL);

        setCpuFrequencyMhz(80); // drop speed when device is 'turned off'

    }    
}

void setBrightnessFromArc(lv_event_t * e)
{
    lv_obj_t * slider = lv_event_get_target(e);
    int32_t percentage = lv_arc_get_value(slider);
        
    Serial.println("setting brightness to: " + String(percentage));
    currentBrightness = percentage;

    set_brightness_percentage(percentage);
}

void setVolumeFromArc(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target(e);
    int32_t percentage = lv_arc_get_value(arc);
    
    Serial.println("Setting volume to: " + String(percentage));
    currentVolume = percentage;
    
    set_volume_percentage(percentage);

    // play sound to verify volume
    play_beep((percentage + 100) * 5, 50);
}

void toggleRotationSettings(lv_event_t * e)
{
    shouldRotate = !shouldRotate;
    saveHardwaveBoolToPreferences("rotation", shouldRotate);
}

void openWifiPortal(lv_event_t * e)
{
    Serial.println("Opening WiFi configuration portal...");

    //show wifi credentials
    displayWifiConnectCredentials(true);

    bool success = start_wifi_portal();

    //hide credentials
    displayWifiConnectCredentials(false);
    
    if (success) {
        Serial.println("WiFi configured!");
        play_beep(1000, 100);  // Success beep
        changeWifiScreenConnected();
    } else {
        Serial.println("WiFi config cancelled/failed");
        play_beep(400, 200);  // Error beep
        show_error_message("Wifi connection failed");
        changeWifiScreenNotConnected();
    }
}

void resetWifiConfig(lv_event_t * e)
{
    Serial.println("Resetting WiFi configuration...");
    show_info_message("Resetting device config");
    reset_wifi_config();
    changeWifiScreenNotConnected();
    play_beep(600, 100);
}

void updateWifiScreenStatusOnLoad(lv_event_t * e) {
    if (is_wifi_connected()) {
        changeWifiScreenConnected();
    } else {
        changeWifiScreenNotConnected();
    }
}

void setButtonsStatusHomeScreen(lv_event_t * e)
{
    changeHomeScreenWifiIcon(is_wifi_connected());
}

void saveBrightness(lv_event_t * e)
{
	saveHardwaveNumberToPreferences("brightness", currentBrightness);
}

void saveVolume(lv_event_t * e)
{
	saveHardwaveNumberToPreferences("volume", currentVolume);
}

void handleScreensScreenLoad(lv_event_t * e)
{
	if(is_wifi_connected()) {
        lv_obj_clear_state(ui_screensRefetchButton, LV_STATE_DISABLED);
        lv_label_set_text(ui_screenNotFetchedLabel, "No screens");
    } else {
        lv_obj_add_state(ui_screensRefetchButton, LV_STATE_DISABLED);
        lv_label_set_text(ui_screenNotFetchedLabel, "No wifi...");
    }
}

void refetchScreens(lv_event_t * e)
{
    display_message("Fetching screens...", MessageSeverity::INFO);
    bool successful = get_screens_from_backend();
    destroy_message();

    if (successful) {
        show_success_message("Screens updated");
    }

    updateScreensScreenOnDataFetch(successful);
}

void swipeNextScreen(lv_event_t * e)
{
	go_next_screen();
}

void swipePrevScreen(lv_event_t * e)
{
	go_prev_screen();
}

void requestScreenDataRefresh(lv_event_t * e)
{
	updateScreenForce();
}

void exitMarketDataSetting(lv_event_t * e)
{
    go_back_from_market_data_setting();
}

void marketDataSettingScreenLoad(lv_event_t * e)
{
	updateMarketDataSettingsScreenOnLoad(get_active_screen());
}

void simpleDisplaySwitchToggle(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);
    bool isSwitchedOn = lv_obj_has_state(sw, LV_STATE_CHECKED);
    updateSimpleDisplay(isSwitchedOn, get_active_screen());
}

void displayGraphSwitchToggle(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);
    bool isSwitchedOn = lv_obj_has_state(sw, LV_STATE_CHECKED);
    updateDispalyGraph(isSwitchedOn, get_active_screen());
}

void candleChartSwitchToggle(lv_event_t * e)
{
    lv_obj_t * sw = lv_event_get_target(e);
    bool isSwitchedOn = lv_obj_has_state(sw, LV_STATE_CHECKED);
    updateCandleGraph(isSwitchedOn, get_active_screen());
}

void switchToHomeScreen(lv_event_t * e)
{
	// Your code here
    go_to_home_screen();
    Serial.println("Long pressed screen - switching to home screen!");

}

void timerResetPressed(lv_event_t * e)
{
    resetTimer(get_active_screen());
}

void timerStartPressed(lv_event_t * e)
{
	startTimerToggle(get_active_screen());
}

void restartDevice(lv_event_t * e)
{
    show_info_message("Restarting device");
    delay(400);
	ESP.restart();
}
