// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homeScreen
extern void ui_homeScreen_screen_init(void);
extern void ui_homeScreen_screen_destroy(void);
extern void ui_event_homeScreen(lv_event_t * e);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_homeLabel;
extern lv_obj_t * ui_homeContainerMain;
extern lv_obj_t * ui_Panel1;
extern void ui_event_turnOffButton(lv_event_t * e);
extern lv_obj_t * ui_turnOffButton;
extern void ui_event_restartButton(lv_event_t * e);
extern lv_obj_t * ui_restartButton;
extern lv_obj_t * ui_homeContainerRow1;
extern void ui_event_brightnessButton(lv_event_t * e);
extern lv_obj_t * ui_brightnessButton;
extern void ui_event_volumeButton(lv_event_t * e);
extern lv_obj_t * ui_volumeButton;
extern void ui_event_rotateButton(lv_event_t * e);
extern lv_obj_t * ui_rotateButton;
extern lv_obj_t * ui_homeContainerRow2;
extern void ui_event_screensButton(lv_event_t * e);
extern lv_obj_t * ui_screensButton;
extern lv_obj_t * ui_batteryButton;
extern void ui_event_wifiButton(lv_event_t * e);
extern lv_obj_t * ui_wifiButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

