// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_homeScreen = NULL;
lv_obj_t * ui_homeLabel = NULL;
lv_obj_t * ui_homeContainerMain = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_turnOffButton = NULL;
lv_obj_t * ui_restartButton = NULL;
lv_obj_t * ui_homeContainerRow1 = NULL;
lv_obj_t * ui_brightnessButton = NULL;
lv_obj_t * ui_volumeButton = NULL;
lv_obj_t * ui_rotateButton = NULL;
lv_obj_t * ui_homeContainerRow2 = NULL;
lv_obj_t * ui_screensButton = NULL;
lv_obj_t * ui_batteryButton = NULL;
lv_obj_t * ui_wifiButton = NULL;
// event funtions
void ui_event_homeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        setButtonsStatusHomeScreen(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipeNextScreen(e);
    }
}

void ui_event_turnOffButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggleTurnOff(e);
    }
}

void ui_event_restartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        restartDevice(e);
    }
}

void ui_event_brightnessButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_brightnessScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_brightnessScreen_screen_init);
    }
}

void ui_event_volumeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_volumeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_volumeScreen_screen_init);
    }
}

void ui_event_rotateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        toggleRotationSettings(e);
    }
}

void ui_event_screensButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screensScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screensScreen_screen_init);
    }
}

void ui_event_wifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_wifiScreen_screen_init);
    }
}

// build funtions

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeLabel = lv_label_create(ui_homeScreen);
    lv_obj_set_width(ui_homeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homeLabel, 0);
    lv_obj_set_y(ui_homeLabel, 200);
    lv_obj_set_align(ui_homeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeLabel, "HOME");
    ui_object_set_themeable_style_property(ui_homeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_grayDark);
    ui_object_set_themeable_style_property(ui_homeLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_grayDark);
    lv_obj_set_style_text_font(ui_homeLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeContainerMain = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_homeContainerMain, 400);
    lv_obj_set_height(ui_homeContainerMain, 431);
    lv_obj_set_x(ui_homeContainerMain, 0);
    lv_obj_set_y(ui_homeContainerMain, -15);
    lv_obj_set_align(ui_homeContainerMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_homeContainerMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_homeContainerMain, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homeContainerMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeContainerMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeContainerMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homeContainerMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homeContainerMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_homeContainerMain);
    lv_obj_set_width(ui_Panel1, 279);
    lv_obj_set_height(ui_Panel1, 137);
    lv_obj_set_x(ui_Panel1, -50);
    lv_obj_set_y(ui_Panel1, -84);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnOffButton = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_turnOffButton, 100);
    lv_obj_set_height(ui_turnOffButton, 100);
    lv_obj_set_align(ui_turnOffButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turnOffButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_turnOffButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_turnOffButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_turnOffButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_redDark);
    ui_object_set_themeable_style_property(ui_turnOffButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_redDark);
    lv_obj_set_style_bg_img_src(ui_turnOffButton, &ui_img_1314322640, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_turnOffButton, lv_color_hex(0xD93737), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_turnOffButton, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_turnOffButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_turnOffButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_turnOffButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_turnOffButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_restartButton = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_restartButton, 100);
    lv_obj_set_height(ui_restartButton, 100);
    lv_obj_set_x(ui_restartButton, 255);
    lv_obj_set_y(ui_restartButton, -148);
    lv_obj_set_align(ui_restartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_restartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_restartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_restartButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_restartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_redDark);
    ui_object_set_themeable_style_property(ui_restartButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_redDark);
    lv_obj_set_style_bg_img_src(ui_restartButton, &ui_img_650757212, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_restartButton, lv_color_hex(0xD93737), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_restartButton, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_restartButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_restartButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_restartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_restartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeContainerRow1 = lv_obj_create(ui_homeContainerMain);
    lv_obj_set_width(ui_homeContainerRow1, 400);
    lv_obj_set_height(ui_homeContainerRow1, 120);
    lv_obj_set_x(ui_homeContainerRow1, -1);
    lv_obj_set_y(ui_homeContainerRow1, 6);
    lv_obj_set_align(ui_homeContainerRow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_homeContainerRow1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_homeContainerRow1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homeContainerRow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeContainerRow1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeContainerRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homeContainerRow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homeContainerRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessButton = lv_btn_create(ui_homeContainerRow1);
    lv_obj_set_width(ui_brightnessButton, 90);
    lv_obj_set_height(ui_brightnessButton, 90);
    lv_obj_set_x(ui_brightnessButton, -19);
    lv_obj_set_y(ui_brightnessButton, -18);
    lv_obj_set_align(ui_brightnessButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightnessButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_brightnessButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_brightnessButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_brightnessButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_brightnessButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_brightnessButton, &ui_img_1826884842, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeButton = lv_btn_create(ui_homeContainerRow1);
    lv_obj_set_width(ui_volumeButton, 90);
    lv_obj_set_height(ui_volumeButton, 90);
    lv_obj_set_x(ui_volumeButton, 19);
    lv_obj_set_y(ui_volumeButton, -17);
    lv_obj_set_align(ui_volumeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_volumeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_volumeButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_volumeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_volumeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_volumeButton, &ui_img_367695115, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rotateButton = lv_btn_create(ui_homeContainerRow1);
    lv_obj_set_width(ui_rotateButton, 90);
    lv_obj_set_height(ui_rotateButton, 90);
    lv_obj_set_x(ui_rotateButton, 19);
    lv_obj_set_y(ui_rotateButton, -17);
    lv_obj_set_align(ui_rotateButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_rotateButton, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_rotateButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rotateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rotateButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rotateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_rotateButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_rotateButton, &ui_img_871200326, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rotateButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_rotateButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_homeContainerRow2 = lv_obj_create(ui_homeContainerMain);
    lv_obj_set_width(ui_homeContainerRow2, 400);
    lv_obj_set_height(ui_homeContainerRow2, 120);
    lv_obj_set_x(ui_homeContainerRow2, -1);
    lv_obj_set_y(ui_homeContainerRow2, 5);
    lv_obj_set_align(ui_homeContainerRow2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_homeContainerRow2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_homeContainerRow2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homeContainerRow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeContainerRow2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeContainerRow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homeContainerRow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homeContainerRow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screensButton = lv_btn_create(ui_homeContainerRow2);
    lv_obj_set_width(ui_screensButton, 90);
    lv_obj_set_height(ui_screensButton, 90);
    lv_obj_set_x(ui_screensButton, 19);
    lv_obj_set_y(ui_screensButton, -17);
    lv_obj_set_align(ui_screensButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screensButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_screensButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screensButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screensButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_screensButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_screensButton, &ui_img_555948897, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_screensButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_screensButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_batteryButton = lv_btn_create(ui_homeContainerRow2);
    lv_obj_set_width(ui_batteryButton, 90);
    lv_obj_set_height(ui_batteryButton, 90);
    lv_obj_set_x(ui_batteryButton, 19);
    lv_obj_set_y(ui_batteryButton, -17);
    lv_obj_set_align(ui_batteryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_batteryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_batteryButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_batteryButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_batteryButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_batteryButton, &ui_img_301975032, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_batteryButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_batteryButton, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_wifiButton = lv_btn_create(ui_homeContainerRow2);
    lv_obj_set_width(ui_wifiButton, 90);
    lv_obj_set_height(ui_wifiButton, 90);
    lv_obj_set_x(ui_wifiButton, -19);
    lv_obj_set_y(ui_wifiButton, -18);
    lv_obj_set_align(ui_wifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_wifiButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_wifiButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_wifiButton, &ui_img_1272477160, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_turnOffButton, ui_event_turnOffButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_restartButton, ui_event_restartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightnessButton, ui_event_brightnessButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeButton, ui_event_volumeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rotateButton, ui_event_rotateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screensButton, ui_event_screensButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiButton, ui_event_wifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeScreen, ui_event_homeScreen, LV_EVENT_ALL, NULL);

}

void ui_homeScreen_screen_destroy(void)
{
    if(ui_homeScreen) lv_obj_del(ui_homeScreen);

    // NULL screen variables
    ui_homeScreen = NULL;
    ui_homeLabel = NULL;
    ui_homeContainerMain = NULL;
    ui_Panel1 = NULL;
    ui_turnOffButton = NULL;
    ui_restartButton = NULL;
    ui_homeContainerRow1 = NULL;
    ui_brightnessButton = NULL;
    ui_volumeButton = NULL;
    ui_rotateButton = NULL;
    ui_homeContainerRow2 = NULL;
    ui_screensButton = NULL;
    ui_batteryButton = NULL;
    ui_wifiButton = NULL;

}
