// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#ifndef UI_TIMERSCREEN_H
#define UI_TIMERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_timerScreen
extern void ui_timerScreen_screen_init(void);
extern void ui_timerScreen_screen_destroy(void);
extern void ui_event_timerScreen(lv_event_t * e);
extern lv_obj_t * ui_timerScreen;
extern lv_obj_t * ui_timerDescriptionSelectorLabel;
extern lv_obj_t * ui_timerNameLabel;
extern lv_obj_t * ui_timerArc;
extern lv_obj_t * ui_timerRollersPanel;
extern lv_obj_t * ui_hourRoller;
extern lv_obj_t * ui_minuteRoller;
extern lv_obj_t * ui_secondRoller;
extern lv_obj_t * ui_timerButtonsPanel;
extern void ui_event_timerResetButton(lv_event_t * e);
extern lv_obj_t * ui_timerResetButton;
extern void ui_event_timerPlayPauseButton(lv_event_t * e);
extern lv_obj_t * ui_timerPlayPauseButton;
extern lv_obj_t * ui_timerTimeLabel;
extern lv_obj_t * ui_timerIcon;
extern lv_obj_t * ui_pauseIconForLoadUnused;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

