// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: market_viewer

#include "ui.h"

lv_obj_t * ui_timerScreen = NULL;
lv_obj_t * ui_timerDescriptionSelectorLabel = NULL;
lv_obj_t * ui_timerNameLabel = NULL;
lv_obj_t * ui_timerArc = NULL;
lv_obj_t * ui_timerRollersPanel = NULL;
lv_obj_t * ui_hourRoller = NULL;
lv_obj_t * ui_minuteRoller = NULL;
lv_obj_t * ui_secondRoller = NULL;
lv_obj_t * ui_timerButtonsPanel = NULL;
lv_obj_t * ui_timerResetButton = NULL;
lv_obj_t * ui_timerPlayPauseButton = NULL;
lv_obj_t * ui_timerTimeLabel = NULL;
lv_obj_t * ui_timerIcon = NULL;
lv_obj_t * ui_pauseIconForLoadUnused = NULL;
// event funtions
void ui_event_timerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipeNextScreen(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        swipePrevScreen(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        switchToHomeScreen(e);
    }
}

void ui_event_timerResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        timerResetPressed(e);
    }
}

void ui_event_timerPlayPauseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        timerStartPressed(e);
    }
}

// build funtions

void ui_timerScreen_screen_init(void)
{
    ui_timerScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_timerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timerScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerDescriptionSelectorLabel = lv_label_create(ui_timerScreen);
    lv_obj_set_width(ui_timerDescriptionSelectorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timerDescriptionSelectorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timerDescriptionSelectorLabel, -4);
    lv_obj_set_y(ui_timerDescriptionSelectorLabel, -150);
    lv_obj_set_align(ui_timerDescriptionSelectorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timerDescriptionSelectorLabel, "H : M : S");
    ui_object_set_themeable_style_property(ui_timerDescriptionSelectorLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_timerDescriptionSelectorLabel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_grayBright);
    lv_obj_set_style_text_letter_space(ui_timerDescriptionSelectorLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_timerDescriptionSelectorLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timerDescriptionSelectorLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerNameLabel = lv_label_create(ui_timerScreen);
    lv_obj_set_width(ui_timerNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timerNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timerNameLabel, 0);
    lv_obj_set_y(ui_timerNameLabel, -90);
    lv_obj_set_align(ui_timerNameLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_timerNameLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_timerNameLabel, "");
    lv_obj_add_flag(ui_timerNameLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_timerNameLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timerNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timerNameLabel, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerArc = lv_arc_create(ui_timerScreen);
    lv_obj_set_width(ui_timerArc, 466);
    lv_obj_set_height(ui_timerArc, 466);
    lv_obj_set_x(ui_timerArc, 1);
    lv_obj_set_y(ui_timerArc, 0);
    lv_obj_set_align(ui_timerArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timerArc, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_timerArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_timerArc, 0, 1000);
    lv_arc_set_value(ui_timerArc, 0);
    lv_arc_set_bg_angles(ui_timerArc, 270, 269);
    lv_arc_set_mode(ui_timerArc, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_width(ui_timerArc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_timerArc, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_yellowBright);
    ui_object_set_themeable_style_property(ui_timerArc, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_yellowBright);
    lv_obj_set_style_arc_width(ui_timerArc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_timerArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timerArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_timerRollersPanel = lv_obj_create(ui_timerScreen);
    lv_obj_set_width(ui_timerRollersPanel, 365);
    lv_obj_set_height(ui_timerRollersPanel, 205);
    lv_obj_set_x(ui_timerRollersPanel, 0);
    lv_obj_set_y(ui_timerRollersPanel, -25);
    lv_obj_set_align(ui_timerRollersPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_timerRollersPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timerRollersPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timerRollersPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timerRollersPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timerRollersPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timerRollersPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timerRollersPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourRoller = lv_roller_create(ui_timerRollersPanel);
    lv_roller_set_options(ui_hourRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_hourRoller, 94);
    lv_obj_set_height(ui_hourRoller, 180);
    lv_obj_set_x(ui_hourRoller, -120);
    lv_obj_set_y(ui_hourRoller, -30);
    lv_obj_set_align(ui_hourRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_hourRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hourRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hourRoller, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hourRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_hourRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_hourRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_hourRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_minuteRoller = lv_roller_create(ui_timerRollersPanel);
    lv_roller_set_options(ui_minuteRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_minuteRoller, 94);
    lv_obj_set_height(ui_minuteRoller, 180);
    lv_obj_set_x(ui_minuteRoller, 0);
    lv_obj_set_y(ui_minuteRoller, -30);
    lv_obj_set_align(ui_minuteRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_minuteRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minuteRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minuteRoller, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minuteRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minuteRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minuteRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_minuteRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_minuteRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_minuteRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_secondRoller = lv_roller_create(ui_timerRollersPanel);
    lv_roller_set_options(ui_secondRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_secondRoller, 94);
    lv_obj_set_height(ui_secondRoller, 180);
    lv_obj_set_x(ui_secondRoller, 120);
    lv_obj_set_y(ui_secondRoller, -30);
    lv_obj_set_align(ui_secondRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_secondRoller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondRoller, &ui_font_mono40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_secondRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_secondRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_secondRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_secondRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_secondRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_secondRoller, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);

    ui_timerButtonsPanel = lv_obj_create(ui_timerScreen);
    lv_obj_set_width(ui_timerButtonsPanel, 249);
    lv_obj_set_height(ui_timerButtonsPanel, 97);
    lv_obj_set_x(ui_timerButtonsPanel, 0);
    lv_obj_set_y(ui_timerButtonsPanel, 120);
    lv_obj_set_align(ui_timerButtonsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_timerButtonsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timerButtonsPanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timerButtonsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timerButtonsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timerButtonsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timerButtonsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerResetButton = lv_btn_create(ui_timerButtonsPanel);
    lv_obj_set_width(ui_timerResetButton, 90);
    lv_obj_set_height(ui_timerResetButton, 90);
    lv_obj_set_x(ui_timerResetButton, 12);
    lv_obj_set_y(ui_timerResetButton, 110);
    lv_obj_set_align(ui_timerResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timerResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timerResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_timerResetButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_timerResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_grayBright);
    ui_object_set_themeable_style_property(ui_timerResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_grayBright);
    lv_obj_set_style_bg_img_src(ui_timerResetButton, &ui_img_936315526, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerPlayPauseButton = lv_btn_create(ui_timerButtonsPanel);
    lv_obj_set_width(ui_timerPlayPauseButton, 90);
    lv_obj_set_height(ui_timerPlayPauseButton, 90);
    lv_obj_set_x(ui_timerPlayPauseButton, 12);
    lv_obj_set_y(ui_timerPlayPauseButton, 110);
    lv_obj_set_align(ui_timerPlayPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timerPlayPauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timerPlayPauseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_timerPlayPauseButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_timerPlayPauseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_yellowDark);
    ui_object_set_themeable_style_property(ui_timerPlayPauseButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_yellowDark);
    lv_obj_set_style_bg_img_src(ui_timerPlayPauseButton, &ui_img_1970864515, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerTimeLabel = lv_label_create(ui_timerScreen);
    lv_obj_set_width(ui_timerTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timerTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timerTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timerTimeLabel, "");
    lv_obj_add_flag(ui_timerTimeLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_timerTimeLabel, &ui_font_monoBold80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timerIcon = lv_img_create(ui_timerScreen);
    lv_img_set_src(ui_timerIcon, &ui_img_461506120);
    lv_obj_set_width(ui_timerIcon, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_timerIcon, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_timerIcon, 0);
    lv_obj_set_y(ui_timerIcon, -150);
    lv_obj_set_align(ui_timerIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timerIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_timerIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_timerIcon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_timerIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pauseIconForLoadUnused = lv_img_create(ui_timerScreen);
    lv_img_set_src(ui_pauseIconForLoadUnused, &ui_img_81954201);
    lv_obj_set_width(ui_pauseIconForLoadUnused, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_pauseIconForLoadUnused, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_pauseIconForLoadUnused, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pauseIconForLoadUnused, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pauseIconForLoadUnused, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_timerResetButton, ui_event_timerResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timerPlayPauseButton, ui_event_timerPlayPauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timerScreen, ui_event_timerScreen, LV_EVENT_ALL, NULL);

}

void ui_timerScreen_screen_destroy(void)
{
    if(ui_timerScreen) lv_obj_del(ui_timerScreen);

    // NULL screen variables
    ui_timerScreen = NULL;
    ui_timerDescriptionSelectorLabel = NULL;
    ui_timerNameLabel = NULL;
    ui_timerArc = NULL;
    ui_timerRollersPanel = NULL;
    ui_hourRoller = NULL;
    ui_minuteRoller = NULL;
    ui_secondRoller = NULL;
    ui_timerButtonsPanel = NULL;
    ui_timerResetButton = NULL;
    ui_timerPlayPauseButton = NULL;
    ui_timerTimeLabel = NULL;
    ui_timerIcon = NULL;
    ui_pauseIconForLoadUnused = NULL;

}
